<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="5" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:12]&nbsp;&nbsp;测试开始]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:12]&nbsp;&nbsp;初始化系统变量]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
    </line>
    <line>
      <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:14]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
    </line>
  </reporter-output>
  <suite started-at="2021-11-25T06:51:13 UTC" name="ApiLogin" finished-at="2021-11-25T06:51:14 UTC" duration-ms="970">
    <groups>
    </groups>
    <test started-at="2021-11-25T06:51:13 UTC" name="ApiLoginTest" finished-at="2021-11-25T06:51:14 UTC" duration-ms="970">
      <class name="com.qa.api.testcases.LoginTest">
        <test-method signature="loginTest(org.testng.ITestContext, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.api.testcases.LoginTest@413d1baf]" started-at="2021-11-25T06:51:13 UTC" name="loginTest" data-provider="LoginData" finished-at="2021-11-25T06:51:13 UTC" duration-ms="547" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@24959ca4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[用户名密码都为空时]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.util.HttpClientUtil.httpPostCookieUtil(HttpClientUtil.java:506)
at com.qa.api.testcases.LoginTest.login(LoginTest.java:48)
at com.qa.api.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
            </line>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(org.testng.ITestContext, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.api.testcases.LoginTest@413d1baf]" started-at="2021-11-25T06:51:13 UTC" name="loginTest" data-provider="LoginData" finished-at="2021-11-25T06:51:13 UTC" duration-ms="102" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@24959ca4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18937165373]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[用户名输入密码不输入]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.util.HttpClientUtil.httpPostCookieUtil(HttpClientUtil.java:506)
at com.qa.api.testcases.LoginTest.login(LoginTest.java:48)
at com.qa.api.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
            </line>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(org.testng.ITestContext, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.api.testcases.LoginTest@413d1baf]" started-at="2021-11-25T06:51:13 UTC" name="loginTest" data-provider="LoginData" finished-at="2021-11-25T06:51:13 UTC" duration-ms="86" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@24959ca4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[qwe12345]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[用户名不输入密码输入]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.util.HttpClientUtil.httpPostCookieUtil(HttpClientUtil.java:506)
at com.qa.api.testcases.LoginTest.login(LoginTest.java:48)
at com.qa.api.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
            </line>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(org.testng.ITestContext, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.api.testcases.LoginTest@413d1baf]" started-at="2021-11-25T06:51:13 UTC" name="loginTest" data-provider="LoginData" finished-at="2021-11-25T06:51:13 UTC" duration-ms="87" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@24959ca4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18937165373]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[用户名正确密码错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.util.HttpClientUtil.httpPostCookieUtil(HttpClientUtil.java:506)
at com.qa.api.testcases.LoginTest.login(LoginTest.java:48)
at com.qa.api.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
            </line>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(org.testng.ITestContext, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.api.testcases.LoginTest@413d1baf]" started-at="2021-11-25T06:51:13 UTC" name="loginTest" data-provider="LoginData" finished-at="2021-11-25T06:51:14 UTC" duration-ms="89" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@24959ca4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18937165373]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[qwe12345]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[用户名密码都正确]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.util.HttpClientUtil.httpPostCookieUtil(HttpClientUtil.java:506)
at com.qa.api.testcases.LoginTest.login(LoginTest.java:48)
at com.qa.api.testcases.LoginTest.loginTest(LoginTest.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:13]&nbsp;&nbsp;开始调用<b>loginTest</b>函数(ApiLogin::ApiLoginTest::com.qa.api.testcases.LoginTest)]]>
            </line>
            <line>
              <![CDATA[[electronicCustomizationAutoTest&nbsp;2021-11-25 星期四 14:51:14]&nbsp;&nbsp;<b>loginTest</b>函数调用结束]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.qa.api.testcases.LoginTest -->
    </test> <!-- ApiLoginTest -->
  </suite> <!-- ApiLogin -->
</testng-results>
